In [18]:
import pandas as pd
import gdown
import numpy as np

In [20]:
file_id = '1fFG-TzbZtUDuzSiw7g8fq06vo8HHUhGM'
gdown.download(f'https://drive.google.com/uc?id={file_id}', 'final_dataset.csv', quiet=False)

Downloading...
From (original): https://drive.google.com/uc?id=1fFG-TzbZtUDuzSiw7g8fq06vo8HHUhGM
From (redirected): https://drive.google.com/uc?id=1fFG-TzbZtUDuzSiw7g8fq06vo8HHUhGM&confirm=t&uuid=46627c06-1088-433e-97b1-721e644530bc
To: /content/final_dataset.csv
100%|██████████| 702M/702M [00:09<00:00, 70.2MB/s]

'final_dataset.csv'

In [21]:
df=pd.read_csv("/content/final_dataset.csv")

In [22]:
df

,filename,text,up_votes,down_votes,age,gender,accent,duration,mel_energy_mean,mel_energy_std,...,mfcc36_mean,mfcc36_std,mfcc37_mean,mfcc37_std,mfcc38_mean,mfcc38_std,mfcc39_mean,mfcc39_std,mfcc40_mean,mfcc40_std
0,cv-valid-train/sample-000000.mp3,learn to recognize omens and follow them the o...,1,0,NaN,NaN,NaN,NaN,1.091124e+01,6.193774e+01,...,-1.175668,4.492468,-1.691033,3.388836,-0.573369,3.375101,-0.919570,3.718753,-1.794360,3.468382
1,cv-valid-train/sample-000001.mp3,everything in the universe evolved he said,1,0,NaN,NaN,NaN,NaN,1.594811e-02,1.180711e-01,...,-1.706345,2.749205,0.679397,2.673455,-1.329319,2.770438,-0.204571,2.816376,-1.076809,2.276889
2,cv-valid-train/sample-000002.mp3,you came so that you could learn about your dr...,1,0,NaN,NaN,NaN,NaN,5.916816e+00,6.748676e+01,...,-0.125119,3.445736,-1.235761,3.325171,-2.057179,3.712299,0.251120,3.185244,-1.354789,3.150853
3,cv-valid-train/sample-000003.mp3,so now i fear nothing because it was those ome...,1,0,NaN,NaN,NaN,NaN,1.367119e-01,1.671695e+00,...,-0.103494,3.331153,-0.330481,3.340889,-1.102569,2.927078,0.340408,3.120746,-0.645374,2.909502
4,cv-valid-train/sample-000004.mp3,if you start your emails with greetings let me...,3,2,NaN,NaN,NaN,NaN,3.520645e+02,2.071311e+03,...,-1.071185,3.622339,-0.227506,3.650861,-0.751787,2.977302,-0.223634,3.334391,0.175214,3.112308
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
380363,cv-invalid/sample-025398.mp3,well then we've got a problem,0,4,NaN,NaN,NaN,NaN,9.480533e-09,3.978150e-08,...,-0.486955,1.426654,-0.547786,1.246857,0.498574,1.409750,-0.021753,1.212668,1.598049,1.852672
380364,cv-invalid/sample-025399.mp3,the boy was surprised at his thoughts,0,6,NaN,NaN,NaN,NaN,1.099137e-01,7.406676e-01,...,-1.995234,2.701185,-0.846011,2.553930,0.011407,2.536131,0.291027,2.499088,1.072422,2.636961
380365,cv-invalid/sample-025400.mp3,undefined,1,2,NaN,NaN,NaN,NaN,6.226113e+00,7.599648e+01,...,-0.753062,2.778601,-1.193318,2.676164,-1.855811,2.876522,-0.671394,2.565463,0.009431,2.395160
380366,cv-invalid/sample-025401.mp3,but there was something there in his heart tha...,1,5,NaN,NaN,NaN,NaN,1.727122e-01,2.894363e+00,...,-1.611724,3.330988,-1.847168,2.841657,-2.033417,2.532349,-0.395191,2.893525,1.378712,2.653137
380367,cv-invalid/sample-025402.mp3,i'll return just as your father came back to y...,0,3,NaN,NaN,NaN,NaN,0.000000e+00,0.000000e+00,...,0.000148,0.000000,-0.000075,0.000000,-0.000121,0.000000,-0.000206,0.000000,0.000092,0.000000

In [15]:
df['accent'].value_counts()

accent
us                59866
england           29981
indian            11387
australia          8234
canada             7800
scotland           2875
newzealand         2545
african            1877
ireland            1860
philippines         646
wales               622
hongkong            463
malaysia            332
southatlandtic      283
bermuda             281
singapore           182
Name: count, dtype: int64

In [16]:
df['age'].value_counts()

age
twenties     48004
thirties     38023
fourties     21956
fifties      19293
teens         9906
sixties       8556
seventies     2833
eighties       450
Name: count, dtype: int64

In [17]:
df['gender'].value_counts()

gender
male      112917
female     35095
other       1269
Name: count, dtype: int64

In [24]:
new_df = df[
    df.apply(
        lambda row: (row['filename'].split('/')[0] == 'cv-invalid' and row['up_votes'] > row['down_votes']) or
                    (row['filename'].split('/')[0] != 'cv-invalid' and row['up_votes'] >= row['down_votes']),
        axis=1
    )
]

In [44]:
#TEXTDATA
columns_to_drop_text = ['up_votes','down_votes', 'age', 'accent', 'gender', 'duration']
df_dropped1 = new_df.drop(columns=columns_to_drop_text)
text_df = df_dropped1.dropna().reset_index(drop=True)

In [45]:
#GENDERDATA
columns_to_drop_gender = ['up_votes','down_votes', 'age', 'accent', 'duration','text']
df_dropped2 = df.drop(columns=columns_to_drop_gender)
gender_df = df_dropped2.dropna().reset_index(drop=True)

In [46]:
#AGEDATA
columns_to_drop_age = ['up_votes','down_votes', 'accent', 'gender', 'duration','text']
df_dropped3 = df.drop(columns=columns_to_drop_age)
age_df = df_dropped3.dropna().reset_index(drop=True)

In [47]:
#ACCENTDATA
columns_to_drop_accent = ['up_votes','down_votes', 'age', 'gender', 'duration','text']
df_dropped4 = df.drop(columns=columns_to_drop_accent)
accent_df = df_dropped4.dropna().reset_index(drop=True)

In [59]:
#Age preprocessing

In [56]:
filtered_age_df = age_df[age_df['age'].isin(['twenties', 'thirties', 'fourties', 'fifties', 'sixties'])]

In [67]:
# Get the counts after filtering
age_counts = filtered_age_df['age'].value_counts()
print("Filtered age counts:")
print(age_counts)

# Find the minimum count (which should be 'sixties' with 8556)
min_count = age_counts.min()  # Should be 8556

# Create a balanced dataframe by sampling from each age group
balanced_age_df = pd.DataFrame()

for age_group in ['twenties', 'thirties', 'fourties', 'fifties', 'sixties']:
    # Get all rows for this age group
    age_group_df = filtered_age_df[filtered_age_df['age'] == age_group]

    # Sample exactly min_count rows from this group (with random seed for reproducibility)
    sampled_df = age_group_df.sample(n=min_count, random_state=42, replace=False)

    # Add to the balanced dataframe
    balanced_age_df = pd.concat([balanced_age_df, sampled_df])

# Verify the counts are now equal
print("\nBalanced age counts:")
print(balanced_age_df['age'].value_counts())

# Reset the index of the final dataframe
balanced_age_df = balanced_age_df.reset_index(drop=True)

Filtered age counts:
age
twenties    48004
thirties    38023
fourties    21956
fifties     19293
sixties      8556
Name: count, dtype: int64

Balanced age counts:
age
twenties    8556
thirties    8556
fourties    8556
fifties     8556
sixties     8556
Name: count, dtype: int64

In [60]:
#Accent preprocessing

In [ ]:
accent_df['accent'].value_counts()

In [62]:
# First, filter to keep only accents up to 'ireland' in your list
selected_accents = ['us', 'england', 'indian', 'australia', 'canada', 'scotland', 'newzealand', 'african', 'ireland']
filtered_accent_df = accent_df[accent_df['accent'].isin(selected_accents)]

# Get the counts after filtering
accent_counts = filtered_accent_df['accent'].value_counts()
print("Filtered accent counts:")
print(accent_counts)

# Find the minimum count (which should be 'ireland' with 1860)
min_count = accent_counts.min()  # Should be 1860
print(f"\nMinimum count: {min_count}")

# Create a balanced dataframe by sampling from each accent group
balanced_accent_df = pd.DataFrame()

for accent_group in selected_accents:
    # Get all rows for this accent group
    accent_group_df = filtered_accent_df[filtered_accent_df['accent'] == accent_group]

    # Sample exactly min_count rows from this group (with random seed for reproducibility)
    sampled_df = accent_group_df.sample(n=min_count, random_state=42, replace=False)

    # Add to the balanced dataframe
    balanced_accent_df = pd.concat([balanced_accent_df, sampled_df])

# Verify the counts are now equal
print("\nBalanced accent counts:")
print(balanced_accent_df['accent'].value_counts())

# Reset the index of the final dataframe
balanced_accent_df = balanced_accent_df.reset_index(drop=True)

Filtered accent counts:
accent
us            59866
england       29981
indian        11387
australia      8234
canada         7800
scotland       2875
newzealand     2545
african        1877
ireland        1860
Name: count, dtype: int64

Minimum count: 1860

Balanced accent counts:
accent
us            1860
england       1860
indian        1860
australia     1860
canada        1860
scotland      1860
newzealand    1860
african       1860
ireland       1860
Name: count, dtype: int64

In [63]:
#Gender Preprocessing

In [64]:
gender_df['gender'].value_counts()

gender
male      112917
female     35095
other       1269
Name: count, dtype: int64

In [65]:
# First, filter to keep only 'male' and 'female'
selected_genders = ['male', 'female']
filtered_gender_df = gender_df[gender_df['gender'].isin(selected_genders)]

# Get the counts after filtering
gender_counts = filtered_gender_df['gender'].value_counts()
print("Filtered gender counts:")
print(gender_counts)

# Find the minimum count (which should be 'female' with 35095)
min_count = gender_counts.min()  # Should be 35095
print(f"\nMinimum count: {min_count}")

# Create a balanced dataframe by sampling from each gender group
balanced_gender_df = pd.DataFrame()

for gender_group in selected_genders:
    # Get all rows for this gender group
    gender_group_df = filtered_gender_df[filtered_gender_df['gender'] == gender_group]

    # Sample exactly min_count rows from this group (with random seed for reproducibility)
    sampled_df = gender_group_df.sample(n=min_count, random_state=42, replace=False)

    # Add to the balanced dataframe
    balanced_gender_df = pd.concat([balanced_gender_df, sampled_df])

# Verify the counts are now equal
print("\nBalanced gender counts:")
print(balanced_gender_df['gender'].value_counts())

# Reset the index of the final dataframe
balanced_gender_df = balanced_gender_df.reset_index(drop=True)

Filtered gender counts:
gender
male      112917
female     35095
Name: count, dtype: int64

Minimum count: 35095

Balanced gender counts:
gender
male      35095
female    35095
Name: count, dtype: int64

In [75]:
balanced_gender_df
balanced_accent_df
balanced_age_df

97

In [82]:
balanced_gender_features = ['gender',
    # Pitch & voice quality
    'pitch_mean', 'pitch_std', 'pitch_range', 'jitter_local', 'voiced_fraction',
    # Spectral/energy
    'spectral_centroid_mean', 'spectral_centroid_std', 'mel_energy_mean', 'rms_mean', 'zero_crossing_rate',
    # MFCC 1-13 (mean + std)
    'mfcc1_mean', 'mfcc1_std', 'mfcc2_mean', 'mfcc2_std', 'mfcc3_mean', 'mfcc3_std',
    'mfcc4_mean', 'mfcc4_std', 'mfcc5_mean', 'mfcc5_std', 'mfcc6_mean', 'mfcc6_std',
    'mfcc7_mean', 'mfcc7_std', 'mfcc8_mean', 'mfcc8_std', 'mfcc9_mean', 'mfcc9_std',
    'mfcc10_mean', 'mfcc10_std', 'mfcc11_mean', 'mfcc11_std', 'mfcc12_mean', 'mfcc12_std',
    'mfcc13_mean', 'mfcc13_std'
]
balanced_gender_df[balanced_gender_features]

,gender,pitch_mean,pitch_std,pitch_range,jitter_local,voiced_fraction,spectral_centroid_mean,spectral_centroid_std,mel_energy_mean,rms_mean,...,mfcc9_mean,mfcc9_std,mfcc10_mean,mfcc10_std,mfcc11_mean,mfcc11_std,mfcc12_mean,mfcc12_std,mfcc13_mean,mfcc13_std
0,male,1286.724854,1194.959595,2567.901367,0.025356,1.524064,6298.615723,664.862854,1.020092,0.015280,...,-4.067001,9.906964,1.400119,6.495378,3.968248,6.210742,-2.024148,4.729501,-2.285295,6.593937
1,male,1089.150879,1001.358643,2533.333496,0.039448,1.524064,3554.466309,317.933014,1.947704,0.015982,...,-10.521035,8.645432,0.462715,8.155013,-1.826335,7.642947,-3.806593,5.958462,4.342268,6.202847
2,male,1251.903076,1194.427979,2547.263672,0.020368,1.524064,1919.245605,502.592224,2.428017,0.021901,...,-2.927802,7.419227,-10.780109,9.683095,-8.224145,9.094098,1.685500,8.928823,-2.187672,6.406533
3,male,148.145126,58.301872,536.774170,0.023312,1.524064,6252.536133,332.607758,82.351105,0.119584,...,-4.546628,6.118995,-8.532826,8.365584,-5.112104,7.457121,-5.337355,7.185544,-2.107265,5.518292
4,male,323.103851,587.899536,2557.077637,0.040057,1.524064,4616.873047,630.461670,7.443396,0.046851,...,-23.746138,16.529491,-5.107903,10.693583,-2.468297,9.165997,-11.184721,9.718652,0.718184,8.427711
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70185,female,721.474609,740.753784,2478.431396,0.081819,1.524064,5116.633789,1167.035645,16.038818,0.068894,...,-21.568296,15.943130,2.743400,10.492778,9.666866,11.310723,-11.014524,11.090086,-6.626025,9.541382
70186,female,1800.514526,1145.079590,2550.724609,0.010167,1.524064,3235.140625,407.444061,2.841254,0.020529,...,-1.589980,6.916872,-6.988491,7.738028,-2.455042,6.123450,-1.847346,4.997891,-6.305168,6.946194
70187,female,1700.217529,1162.881836,2434.782715,0.010391,1.524064,3577.963379,583.000244,6.004779,0.033836,...,-14.222166,15.336505,0.878697,7.618025,-0.945417,8.989024,-1.890150,5.742150,4.835901,7.602734
70188,female,1776.941284,1134.470703,2560.706543,0.027640,1.524064,5361.672363,512.267639,0.538726,0.010721,...,-7.324463,11.106894,-4.351950,9.055223,-0.895720,7.575522,-5.904900,7.581466,-2.730467,6.896881
70189,female,724.351562,861.893250,2540.682617,0.076846,1.524064,5342.111816,603.707336,11.757727,0.056782,...,2.380352,10.831221,-18.452740,12.341392,-6.509687,9.468727,-4.311360,7.408374,-4.835406,7.126785

In [79]:
balanced_accent_features = [
    # Prosody/Pitch
    'pitch_mean', 'pitch_std', 'pitch_range', 'jitter_local',
    # Spectral
    'spectral_centroid_mean', 'spectral_centroid_std', 'spectral_flux',
    # Energy
    'mel_energy_mean', 'rms_mean', 'energy_variability',
    # Temporal
    'zero_crossing_rate', 'voiced_fraction',
    # MFCCs (1-20, mean + std)
    'mfcc1_mean', 'mfcc1_std', 'mfcc2_mean', 'mfcc2_std',
    'mfcc3_mean', 'mfcc3_std', 'mfcc4_mean', 'mfcc4_std',
    'mfcc5_mean', 'mfcc5_std', 'mfcc6_mean', 'mfcc6_std',
    'mfcc7_mean', 'mfcc7_std', 'mfcc8_mean', 'mfcc8_std',
    'mfcc9_mean', 'mfcc9_std', 'mfcc10_mean', 'mfcc10_std',
    'mfcc11_mean', 'mfcc11_std', 'mfcc12_mean', 'mfcc12_std',
    'mfcc13_mean', 'mfcc13_std', 'mfcc14_mean', 'mfcc14_std',
    'mfcc15_mean', 'mfcc15_std', 'mfcc16_mean', 'mfcc16_std',
    'mfcc17_mean', 'mfcc17_std', 'mfcc18_mean', 'mfcc18_std',
    'mfcc19_mean', 'mfcc19_std', 'mfcc20_mean', 'mfcc20_std'
]
balanced_accent_df[balanced_accent_features]

,pitch_mean,pitch_std,pitch_range,jitter_local,spectral_centroid_mean,spectral_centroid_std,spectral_flux,mel_energy_mean,rms_mean,energy_variability,...,mfcc16_mean,mfcc16_std,mfcc17_mean,mfcc17_std,mfcc18_mean,mfcc18_std,mfcc19_mean,mfcc19_std,mfcc20_mean,mfcc20_std
0,1347.151733,1165.475708,2531.073486,0.036009,5103.631348,830.792664,2.227945,2.145052,0.030338,0.729849,...,-0.633097,5.598220,4.537169,5.980547,2.092499,5.611379,-2.468636,6.344419,4.882935,4.979856
1,1075.680664,1060.279175,2548.148193,0.070135,3750.699219,459.641754,285.949677,9.015863,0.052497,1.069720,...,0.757544,7.052895,-2.889278,6.781746,-4.006464,5.215297,2.848341,6.519088,-0.478561,4.898427
2,984.231812,1068.144653,2574.712646,0.021710,2810.648438,789.617249,0.592251,0.909437,0.015657,1.200450,...,-6.842062,8.387463,7.477962,7.307454,-6.353094,7.860423,-0.434991,6.946858,4.993043,6.213027
3,200.062408,145.820801,1482.352905,0.096579,4586.806641,614.628601,741.495972,12.440523,0.054565,1.318880,...,-6.895418,5.667967,7.298892,4.255522,-8.012538,5.502467,3.780025,5.669793,-1.960509,4.106042
4,498.588165,376.221863,1488.888916,0.131135,6148.637695,456.284943,0.892298,0.992169,0.012631,1.762053,...,1.311293,5.901263,-1.132430,5.247204,-3.295457,5.526327,0.163785,5.115503,-1.209954,4.906193
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16735,805.675171,956.080505,2574.181152,0.063261,3941.644043,927.472961,5.204850,2.493094,0.026709,1.137151,...,-9.814474,8.518498,2.300608,6.867180,-7.682689,6.812063,-1.562539,5.892694,-3.893659,5.393634
16736,296.874573,382.694763,2576.779053,0.109363,3920.900635,701.479614,59.112961,9.354297,0.051657,1.151091,...,-8.752336,8.745362,1.518507,5.617329,-6.676625,5.918149,1.051001,6.334279,-0.373388,5.266445
16737,247.312622,314.395294,1668.188843,0.055794,4911.203613,675.359863,1.462632,1.800260,0.025582,0.904523,...,-3.934868,7.460098,-8.800423,8.386734,0.605841,7.379430,3.313567,7.265800,0.777370,5.665621
16738,951.143250,1120.997559,2580.180176,0.037757,2499.245850,590.655518,0.000014,0.003363,0.000898,1.322296,...,-3.351762,5.819760,-0.584625,6.755215,-6.707709,8.439560,3.072986,6.946875,-1.658579,4.511371
16739,559.694214,730.870850,2185.714355,0.097587,5150.600586,1225.400635,313.848694,14.428922,0.057206,1.380857,...,-2.158555,6.448267,-2.509076,4.933703,-1.657285,6.571698,-0.360007,6.728150,-0.789387,5.405529

In [81]:
balanced_age_features = ['age',
    # Pitch & stability
    'pitch_mean', 'pitch_std', 'pitch_range', 'jitter_local',
    # Spectral
    'spectral_centroid_mean', 'spectral_centroid_std', 'spectral_flux',
    # Energy
    'mel_energy_mean', 'rms_mean', 'energy_variability',
    # Voice quality
    'voiced_fraction', 'zero_crossing_rate',
    # MFCCs (1-16, mean + std)
    'mfcc1_mean', 'mfcc1_std', 'mfcc2_mean', 'mfcc2_std',
    'mfcc3_mean', 'mfcc3_std', 'mfcc4_mean', 'mfcc4_std',
    'mfcc5_mean', 'mfcc5_std', 'mfcc6_mean', 'mfcc6_std',
    'mfcc7_mean', 'mfcc7_std', 'mfcc8_mean', 'mfcc8_std',
    'mfcc9_mean', 'mfcc9_std', 'mfcc10_mean', 'mfcc10_std',
    'mfcc11_mean', 'mfcc11_std', 'mfcc12_mean', 'mfcc12_std',
    'mfcc13_mean', 'mfcc13_std', 'mfcc14_mean', 'mfcc14_std',
    'mfcc15_mean', 'mfcc15_std', 'mfcc16_mean', 'mfcc16_std'
]
balanced_age_df[balanced_age_features]

,age,pitch_mean,pitch_std,pitch_range,jitter_local,spectral_centroid_mean,spectral_centroid_std,spectral_flux,mel_energy_mean,rms_mean,...,mfcc12_mean,mfcc12_std,mfcc13_mean,mfcc13_std,mfcc14_mean,mfcc14_std,mfcc15_mean,mfcc15_std,mfcc16_mean,mfcc16_std
0,twenties,799.646057,1079.394653,2552.381104,0.035610,3537.491455,829.898193,135.853897,14.861291,0.077783,...,-2.384443,10.063907,-4.402807,7.656124,-11.234600,9.979306,1.545701,8.262005,-2.059768,8.571908
1,twenties,1026.427002,1017.334900,2546.365967,0.064063,2779.546875,596.100708,6.312774,2.194625,0.024289,...,-3.397267,8.206078,-6.484622,9.096119,-0.053821,6.732479,3.759134,7.252732,-0.759468,8.084679
2,twenties,475.026428,785.611877,2578.754639,0.077130,4131.056152,817.596252,192.917725,14.604396,0.076455,...,-1.847027,9.922668,-2.764870,7.551832,0.051133,7.549807,-0.205069,7.547809,4.677394,6.616945
3,twenties,511.933136,771.618530,2549.019775,0.062365,4404.934570,840.803528,193.788956,9.267547,0.046453,...,-7.447856,9.273422,-0.682012,7.906982,-2.329798,6.314481,-2.620621,6.489893,-2.552274,6.009437
4,twenties,258.187927,205.863983,1888.888916,0.097586,4345.276855,934.997314,0.006573,0.039278,0.003021,...,-7.429379,7.289770,-0.610556,7.614835,-0.697678,6.020173,-0.561051,6.294272,-1.905531,5.623327
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42775,sixties,938.913635,992.127258,2544.529297,0.041072,5663.918945,597.481018,25229.738281,68.072060,0.104227,...,-0.380603,5.902085,-4.582070,7.411378,-5.396848,7.369985,-3.828514,5.315190,-2.099912,4.796669
42776,sixties,890.826233,882.257141,2521.212158,0.040936,5501.150879,631.162964,9.888021,2.505402,0.027217,...,-4.491087,8.046663,-1.780712,6.539967,-3.447175,6.679843,-5.705654,7.459567,-1.039059,6.067225
42777,sixties,478.041565,754.620361,2582.010742,0.112553,5790.331055,1099.703003,38.283585,8.590426,0.048057,...,-16.948502,10.627110,-4.652145,8.198269,-0.881522,6.791039,-5.627606,7.040823,-1.960810,7.061335
42778,sixties,447.789093,420.401245,1139.860229,0.028472,4660.513672,1147.241821,9.631743,2.208853,0.025249,...,-5.589175,7.653767,-9.170856,9.371760,-6.220240,7.742624,-5.536332,8.437874,-0.176451,5.750590
42779,sixties,1069.722046,1119.277222,2521.212158,0.028919,5813.796875,763.072754,8.426325,2.200135,0.025751,...,-4.537748,7.706846,-3.655126,8.889007,-2.179217,7.116785,-8.084694,8.892141,0.400506,5.684247